# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Partidos Públicos
email: prensa@ciudadanointeligente.org
description: 'Partidos Públicos es una plataforma web que busca reivindicar la importancia de partidos transparentes, participativos y abiertos para una sana democracia.'
baseurl: '//partidospublicos.cl' #"//ciudadanointeligente.github.io/partidos-lanzamiento/"
basedomain: partidospublicos.cl
analytics:

# Build settings
markdown: kramdown
